baseurl = "https://zealousfashion.biz"
defaultContentLanguage = "en"
languageCode = "en"
title = "Zealous Fashion"
theme = "dream"

[permalinks]
    categories =  "/:section/:slug"
    posts = "clothing-prints/:title"
    pages = "/:slug"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Heather"
# description = ""
avatar = "images/zealous.jpg"
headerTitle = "Zealous Fashion"
motto = "Screen Printing and Custom Clothing Prints in Nanaimo, BC "

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2017

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
showSummaryCoverInPost = true
# showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

[params.navItems]
nanaimo = { href = "/nanaimo-screen-printing", icon = "location", title = "Nanaimo" }

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy-MM-dd"
